language: generic

matrix:
  include:
    - os: linux
    - os: osx
      env:
        - PYTHON_VERSION=2.7.11
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=2.7.11
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.4.4
    - os: osx
      env:
        - PYTHON_VERSION=3.4.4
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.5.1
    - os: osx
      env:
        - PYTHON_VERSION=3.5.1
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.6.0
        - VENV=venv
    - os: osx
      env:
        - PYPY_VERSION=2.6
        - VENV=venv
    - os: osx
      env:
        - PYPY_VERSION=4.0
        - VENV=venv
    - os: osx
      env:
        - PYPY_VERSION=5.0
        - VENV=venv
    - os: osx
      env:
        - PYPY_VERSION=5.1
        - VENV=venv
    - os: osx
      env:
        - PYPY_VERSION=5.3
        - VENV=venv
    - os: osx
      env:
        - PYPY_VERSION=5.4
        - VENV=venv
    - os: osx
      env:
        - PYPY_VERSION=5.6
        - VENV=venv
    - os: osx
      env:
        - PYPY_VERSION=5.7
        - VENV=venv

script:
  - source tests/test_multibuild.sh
