language: generic

matrix:
  include:
    - os: linux
    - os: osx
      env:
        - PYTHON_VERSION=2.7.11
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=2.7.11
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.4.4
    - os: osx
      env:
        - PYTHON_VERSION=3.4.4
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.5.1
    - os: osx
      env:
        - PYTHON_VERSION=3.5.1
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.6.0
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-2.6
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-4.0
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-5.0
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-5.1
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-5.3
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-5.4
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-5.6
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-5.7
        - VENV=venv

script:
  - source tests/test_multibuild.sh
