# Set TEST_BUILDS=1 to run library_builders tests

language: generic

cache:
  directories:
   - $HOME/.ccache

env:
    global:
        # Always set Python version
        - MB_PYTHON_VERSION=3.7

matrix:
  include:
    - os: linux
      dist: trusty
    # 64-bit builds
    - os: linux
      dist: xenial
      env:
        - TEST_BUILDS=1
    # 64-bit builds, manylinux2010
    - os: linux
      dist: xenial
      env:
        - TEST_BUILDS=1
        - MB_ML_VER=2010
        - MB_TEST_VER=multibuild/xenial
    # 32-bit builds
    - os: linux
      dist: xenial
      env:
        - TEST_BUILDS=1
        - PLAT=i686
    - os: linux
      dist: xenial
      env:
        - TEST_BUILDS=1
        - PLAT=i686
        - MB_ML_VER=2010
        - MB_TEST_VER=multibuild/bionic
    # Builds with caching
    - os: linux
      dist: xenial
      env:
        - TEST_BUILDS=1
        - USE_CCACHE=1
    # Build with pypy3
    - os: linux
      env:
        - MB_PYTHON_VERSION=pypy3.6-7.3
        - MB_ML_VER=2014
        - TEST_BUILDS=1
    # OSX builds
    - os: osx
      env:
        - MB_PYTHON_VERSION=2.7
        - MB_PYTHON_OSX_VER=10.6
        - TEST_BUILDS=1
    - os: osx
      env:
        - MB_PYTHON_VERSION=2.7
        - TEST_BUILDS=1
    - os: osx
      language: objective-c
      env:
        - MB_PYTHON_VERSION=2.7
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.5
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
        - MB_PYTHON_OSX_VER=10.6
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_PYTHON_OSX_VER=10.6
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
        - VENV=venv
        - USE_CCACHE=1
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.8
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-6.0
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-7.0
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-7.1
        - VENV=venv
    - os: osx
      env:
        - MB_PYTHON_VERSION=pypy-7.2
        - TEST_BUILDS=1
        - VENV=venv
    # Default OSX (xcode image) is 10.13 (xcode 9.4.1) as of 2018-08-03
    # See: https://docs.travis-ci.com/user/reference/osx/
    - os: osx
      osx_image: xcode10.1
      env:
        - MB_PYTHON_VERSION=3.7
        - TEST_BUILDS=1
    - os: osx
      osx_image: xcode10.1
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_PYTHON_OSX_VER=10.9
        - TEST_BUILDS=1
    - os: osx
      osx_image: xcode10
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      osx_image: xcode10
      env:
        - MB_PYTHON_VERSION=3.8
    - os: osx
      osx_image: xcode10.1
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode10
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode9.4
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode9.3
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode9.2
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode9.1
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode9
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode8.3
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode8.2
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode8.1
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode8
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode7.3
      env:
        - MB_PYTHON_VERSION=3.5
    # ARM aarch 64 builds
    - os: linux
      arch: arm64
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_ML_VER=2014
        - TEST_BUILDS=1
        - PLAT=aarch64
    #  s390x builds
    - os: linux
      arch: s390x
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_ML_VER=2014
        - TEST_BUILDS=1
        - PLAT=s390x
    #  ppc64le builds
    - os: linux
      arch: ppc64le
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_ML_VER=2014
        - TEST_BUILDS=1
        - PLAT=ppc64le

script:
  - export ENV_VARS_PATH="tests/env_vars.sh"
  - source tests/test_multibuild.sh
