# Set TEST_BUILDS=1 to run library_builders tests

language: generic

branches:
  only:
  - master
  - devel
  
cache:
  directories:
   - $HOME/.ccache

matrix:
  include:
    - os: linux
      dist: precise
      env:
        - TEST_BUILDS=1
    - os: linux
      dist: trusty
      env:
        - TEST_BUILDS=1
      sudo: required
    - os: linux
      dist: trusty
      env:
        - TEST_BUILDS=1
        - USE_CCACHE=1
      sudo: required
    - os: osx
      osx_image: xcode6.4
      env:
        - PYTHON_VERSION=2.6
        - TEST_BUILDS=1
    - os: osx
      osx_image: xcode6.4
      env:
        - PYTHON_VERSION=2.6
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=2.7.11
        - TEST_BUILDS=1
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=2.7.11
        - VENV=venv
    - os: osx
      osx_image: xcode6.4
      env:
        - PYTHON_VERSION=3.3
    - os: osx
      env:
        - PYTHON_VERSION=3.4.4
    - os: osx
      env:
        - PYTHON_VERSION=3.4.4
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.5.3
    - os: osx
      env:
        - PYTHON_VERSION=3.5.3
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.6.1
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.6.1
        - VENV=venv
        - USE_CCACHE=1
    - os: osx
      env:
        - PYTHON_VERSION=pypy-2.6
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-4.0
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.0
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.1
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.3
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.4
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.6
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.7
        - VENV=venv
    # Default OSX (xcode image) is 10.11 (xcode 7.3.1) as of 2017-05-02
    # See: https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
    - os: osx
      osx_image: xcode8.3
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode8.2
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode8.1
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode8
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode7.3
      env:
        - PYTHON_VERSION=3.5
    - os: osx
      osx_image: xcode6.4
      env:
        - PYTHON_VERSION=3.5

script:
  - source tests/test_multibuild.sh
